server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: workspace-service
          uri: lb://WORKSPACE-SERVICE
          predicates:
            - Path=/api/workspace/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/